version: '3'

services:
  testdb:
    container_name: "testdb"
    image: mariadb:10.6
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: mydb
      MARIADB_USER: replication_user
      MARIADB_PASSWORD: secret123passwd
    ports:
      - "3306:3306"
    command: |
      --server-id=1
      --default-authentication-plugin=mysql_native_password
      --log-bin=master-bin
      --binlog-format=row
      --log-slave-updates=on
      --binlog-do-db=mydb
    volumes:
      - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql
    networks:
      - mariadb-cluster

networks:
  mariadb-cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.200.0.0/24
